;   --одна команда должны быть, если не будет запросов'

CREATE TABLE IF NOT EXISTS Genre (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR NOT NULL UNIQUE,	--всега нужно указывать значение поля при добавлении/обновлении строки
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Rating (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(5) NOT NULL UNIQUE,	--всега нужно указывать значение поля при добавлении/обновлении строки
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS StatusFriendship (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR NOT NULL UNIQUE,	--всега нужно указывать значение поля при добавлении/обновлении строки
description VARCHAR NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Film (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rating INTEGER NOT NULL REFERENCES Rating (id), --не указываем ON DELETE/UPDATE RESTRICT т.к. по умол.это обеспечит ON ACTION, то есть
										--не будет удалена запись в главной таблице (Rating), если на нее ссылается запись в таблице Film
										--не будет обновлен PK у записи главной таблицы (Rating), если на нее ссылается запись в таблице Film
name VARCHAR NOT NULL CHECK (TRIM('	 ' FROM name) != ''),	--у фильма должно быть наименование, поэтому пустые строки не разрешаем
description VARCHAR(200) NOT NULL DEFAULT '',
releaseDate DATE NOT NULL CHECK (releaseDate >= '1895-12-28'),	--формат по умол. YYYY-MM-DD и вводим нижнюю границу равную выходу первого в истории фильма
duration INTEGER NOT NULL CHECK (duration > 0)	--длительность фильма должна быть больше 0
);

CREATE TABLE IF NOT EXISTS User_ (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--email VARCHAR NOT NULL UNIQUE CHECK (TRIM('	 ' FROM email) != '' AND email LIKE '%@%'),
email VARCHAR NOT NULL CHECK (TRIM('	 ' FROM email) != '' AND email LIKE '%@%'),
--login VARCHAR(116) NOT NULL UNIQUE CHECK (TRIM('	 ' FROM login) != ''),
login VARCHAR(116) NOT NULL CHECK (TRIM('	 ' FROM login) != ''),
name  VARCHAR NOT NULL,
birthday DATE NOT NULL
);
create unique index if not exists USER_EMAIL_UINDEX on User_ (email);
create unique index if not exists USER_LOGIN_UINDEX on User_ (login);

CREATE TABLE IF NOT EXISTS Likes (
film_id INTEGER NOT NULL REFERENCES Film (id),
user_id INTEGER NOT NULL REFERENCES User_ (id),
PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS Film_Genre (
film_id INTEGER NOT NULL REFERENCES Film (id),
genre_id INTEGER NOT NULL REFERENCES Genre (id),
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS Friends (
user_id INTEGER NOT NULL REFERENCES User_ (id),
friend_id INTEGER NOT NULL REFERENCES User_ (id),
status_id INTEGER NOT NULL REFERENCES StatusFriendship (id),
PRIMARY KEY (user_id, friend_id)
);
